Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/new'
  get 'tags/show'
  get 'tags/create'
  get 'tags/edit'
  get 'tags/update'
  get 'locations/index'
  get 'locations/new'
  get 'locations/show'
  get 'locations/create'
  get 'locations/edit'
  get 'locations/update'
  get 'milestones/index'
  get 'milestones/new'
  get 'milestones/show'
  get 'milestones/create'
  get 'milestones/edit'
  get 'milestones/update'
  get 'milestones/destroy'
  get 'contacts/index'
  get 'contacts/new'
  get 'contacts/show'
  get 'contacts/create'
  get 'contacts/edit'
  get 'contacts/update'
  get 'contacts/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
